### ISSUE TITLE
trainers not working under root-config. is there any progress?

### ISSUE THREAD

**Issue by vvenv** [isomorphic-microfrontends/trainers#1]
RT

**Comment by saffari-m** [comment]
@crossjs Hi, do you find any solution?

**Comment by vvenv** [comment]
> @crossjs Hi, do you find any solution?

No :(

**Comment by internettrans** [comment]
The trainers MFE is a NextJS experiment that is not complete. I wouldn't recommend trying it out yet.

**Comment by jovicon** [comment]
Hi @joeldenning hope you are really well, is it possible to run NextJs with single spa today?
